# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image as the base image
FROM node:16-alpine AS builder

# Set the working directory inside the Docker image
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the entire application source
COPY . .

# Build the application
RUN npm run build

# Use a minimal Node.js runtime for the final image
FROM node:16-alpine

# Set the working directory inside the Docker image
WORKDIR /app

# Copy the built application from the builder stage
COPY --from=builder /app/dist /app/dist

# Copy package.json and package-lock.json
COPY --from=builder /app/package.json /app/package-lock.json ./

# Install production dependencies
RUN npm install --production

# Expose the port the app runs on
EXPOSE 3000

# Run the MCP server
CMD ["node", "dist/index.js"]
